- name: varaibles reading from yaml files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: Printing course information
    ansible.builtin.debug:
    msg: "The course: {{ COURSE }}, Duration is : {{ DURATION }}, and trainer is {{ TRAINER }}"
    