- name: to read input from the keyboard
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: Please enter the Course name
    private: false # to show the iput while enter
  - name: DURATION
    prompt: Please enter the duration details
    private: false # to show the iput while enter
  - name: TRAINER  # it won't  show the iput while enter by default
    prompt: Please enter the trainer's name
  tasks:
  - name: print the course details
    ansible.builtin.debug:
     msg: "Name of the Course: {{ COURSE }}, Course duration: {{ DURATION }}, and trainer is {{ TRAINER }} "       
