- name: input read priority
  hosts: local
  connection: local
  # vars:
  #  GREET: "Play area"
  vars_files:
   - course.yaml 
  # vars_prompt:
  #  - name: GREET
  #    prompt: Please enter the input as prompt input
  #    private: false     
  tasks:
  - name: to print input
    # vars:
    #  GREET: "Task area"
    ansible.builtin.debug:
     msg: "The input from the area belogs {{ GREET }}" 