- name: reading different kind of inputs from different patterns
  hosts: local
  connection: local
  vars:
   course_name: "DevSecOps"           #string
   duration: 120hrs                   #number
   trainer: SivaKumar
   topics:                            #list of values , represents in []
    - linux
    - shellscript
    - ansible
    - terraform
    - docker
    - cubernetes
   live: true                         # boolean returns either true or false
   tools:                             # map , reprsents in {}
    ci: jenkins
    cloud: aws
    containerzation: docker
  tasks:
  - name: to print the different mode of inputs
    ansible.builtin.debug:
     msg: "The title of course {{ course_name }}, total no of hours {{ duration }}, trainer is {{ trainer }},the topics covered {{ topics }}is it live {{ live }}, the tools covered are {{ tools }}"    
