- name: reading different kind of inputs from different patterns
  hosts: local
  connection: local
  vars:
   course_name: "DevSecOps"
   duration: 120hrs
   trainer: SivaKumar
   topics:
    - linux
    - shellscript
    - ansible
    - terraform
    - docker
    - cubernetes
  live: true
  tools:
   ci: jenkins
   cloud: aws
   containerzation: docker
  tasks:
  - name: to print the different mode of inputs
    ansible.builtin.debug:
     msg: "The title of course {{ course_name }}, total no of hours {{ duration }}, trainer is {{ trainer }},is it live {{ live }}, the tools covered are {{ tools }}"    
