- name: convert inputs into other format of inputs
  hosts: local
  connection: local
  tasks:
  - name:   managing the undefined variable
    ansible.builtin.debug:
     msg: " Hello {{ person | default('Mahesh') }}"

  - name:   string converts into list
    vars:
     fruits: "Mango,Apple,Gua,Pineapple,Banana"
    ansible.builtin.debug:
     msg: " Hello fruits are {{ fruits | split(',')  }}"

  - name:   converts into list
    vars:
     course: 
      name: "devSecOps"
      duration: 120hrs
      trainer: sivakumarreddy
    ansible.builtin.debug:
      msg: " Hello about course is {{ course | dict2items }}"   

  - name: converts into map
    vars:
     course:
     - {'key': 'name', 'value': 'DevSecOps'}
     - {'key': 'duration', 'value': '12ohrs'}
     - {'key': 'trainer', 'value': 'Sivakumar reddy'}
    ansible.builtin.debug:
     msg: "Hello about course details are {{ course | items2dict }}"

  - name: converts into lowercase letters
    vars:
     name: "Rajabhushanam.yeguru"
    ansible.builtin.debug:
     msg: "My name is {{ name | lower }}"

  - name: converts into uppercase letters
    vars:
     name: "Rajabhushanam.yeguru"
    ansible.builtin.debug:
     msg: "My name is {{ name | upper }}"  

  - name: print the max and min numbers from the list of numbers
    vars:
     numbers: [1,2,3,4,5,6,7,8,9,17]
    ansible.builtin.debug:
     msg: "max number is {{ numbers | max  }}" 
     msg: "minimum number is {{ numbers | min  }}"      

  - name: to validate the ip
    vars:
     ip: "192.168.0.145"
    ansible.builtin.debug:
     msg: "The ip is {{ ip | ansible.utils.ipaddr }}"    
