- name: create ec2 and r53 instances
  hosts: local
  connection: local
  vars:
   subnet_id: subnet-0d5f1a67b68a87025
   sg_id: sg-0406762d7479e6dde
   ami_id: ami-09c813fb71547fc4f
   instance_type: t3.micro
   instances:
   - mysql
   - backend
   - frontend

  tasks: 
  - name: to install AWS Phython libraries
    ansible.builtin.pip:
     name: "{{ item }}"
     executable: pip3.9
    loop:
    - boto3
    - botocore
  - name: create ec2 instances
    amazon.aws.ec2_instance:
     name: "{{ item }}"
     subnet_id: "{{ subnet_id }}"
     security_group: "{{ sg_id }}"
     image_id: "{{ ami_id }}"
     instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
    register: ec2_info
  - name: get info about ec2 info
    ansible.builtin.debug:
    - msg: "{{ ec2_info }}"   


